
version: 2.1
jobs:
  # TODO
  test:
    docker:
      - image: cimg/base:latest
    steps:
      - checkout
  build:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - run:
          name: Set up environment variables
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=roots' >> $BASH_ENV
      - run:
          name: Print environtment variables
          command: |
            echo "$TAG"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: main
